Personal Portfolio Works And About Sections
shaqdeff/Shaquille-Portfolio pull request #4
Opened 2022-03-18 21:51 UTC by shaqdeff

- Created a works and about section using HTML and CSS.
- For the works section, I used CSS Grid and FlexBox as per the requirements.
- As for the about section, 'ul li' were used for the languages categories.
- Set up and checked linters.
- Used best HTML and CSS practices.
- Used proper GitHub flow.

Kindly review and provide feedback if any changes need to be made.

Regards.

2022-03-18 23:12 UTC, Wes-Isaac requested changes
Hi @shaqdeff, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linters are on point ✔
- Splendid work with the README file 👀
- Proper use of GitHub flow 👌
- Awesome design 🙌


## Required Changes ♻️
_Check the comments under the review._
![image](https://user-images.githubusercontent.com/59416136/159095807-57face75-5633-4373-ba21-ea1ea0c262c2.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-18 23:12 UTC, Wes-Isaac commented on index.html
> +      </h1>
- [ ] Great job so far, it's a good practice to have one `h1` in your page, please change this to `<hx>(<h2><h3>..)`

2022-03-18 23:12 UTC, Wes-Isaac commented on index.html
> +      <p>LET'S CONNECT</p>
- [ ] Great job, it's one of the requirements to use `<hx>(<h2><h3>..)` for this. Kindly fix it.

2022-03-19 08:27 UTC, Mre55 approved these changes
**Hi @shaqdeff,**

# Status: APPROVED 🎉 🎊 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

![Alt Text](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 08:33 UTC, merged

2022-03-22 07:37 UTC, joseph07-drack reviewed
Try thinking and implementing the suggestions

2022-03-22 07:37 UTC, joseph07-drack commented on css/styles.css
> +  /* align-items: center; */
Please, do not leave unused code as comments in your codebase to make your codebase cleaner.

2022-03-22 07:37 UTC, joseph07-drack commented on index.html
> +      </section>
Using ```<section>``` inside ```<section>``` is not a good practice. Consider using ```<article>``` instead.
Like ```<section>
               <arcticle></article>
          </section>```